ci: fix workflow issues

diff --git a/.github/workflows/bright.yml b/.github/workflows/bright.yml
--- a/.github/workflows/bright.yml
+++ b/.github/workflows/bright.yml
@@ -113,11 +113,21 @@ jobs:
           npm i --save=false --prefix .brightsec @sectester/core@0.49.0 @sectester/repeater@0.49.0 @sectester/scan@0.49.0 @sectester/runner@0.49.0 @sectester/reporter@0.49.0
 
       - name: Authenticate with Bright
-        uses: ./.github/workflows/composite/configure-bright-credentials
-        with:
+        env:
           BRIGHT_HOSTNAME: development.playground.brightsec.com
           BRIGHT_PROJECT_ID: dhSq9jPULmyZnndTYVtd6o
-          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
+          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
+          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
+        run: |
+          OIDC_TOKEN=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://development.playground.brightsec.com" | jq -r '.value')
+          RESPONSE=$(curl -s -X POST "https://${BRIGHT_HOSTNAME}/api/v1/projects/${BRIGHT_PROJECT_ID}/api-keys/oidc" -H "Content-Type: application/json" -d "{\"token\": \"${OIDC_TOKEN}\"}")
+          if ! echo "$RESPONSE" | jq -e . > /dev/null 2>&1; then
+            echo "Error: $RESPONSE" 1>&2
+            exit 1
+          fi
+          PURE_KEY=$(echo "$RESPONSE" | jq -r '.pureKey')
+          echo "::add-mask::$PURE_KEY"
+          echo "BRIGHT_TOKEN=$PURE_KEY" >> $GITHUB_ENV
 
       - name: Run security tests
         env:
